# Generated by Django 3.1 on 2020-09-03 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30)),
                ('NIN', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('dealers_in', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('size', models.CharField(default=None, max_length=20)),
                ('maker', models.CharField(default=None, max_length=20)),
                ('addedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelvesapp.business')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('RAM', models.CharField(max_length=20)),
                ('storage', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('addedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelvesapp.business')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('storage', models.CharField(max_length=20)),
                ('RAM', models.CharField(max_length=20)),
                ('addedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelvesapp.business')),
            ],
        ),
    ]
