# Generated by Django 3.1 on 2020-09-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelvesapp', '0008_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
