# Generated by Django 3.1 on 2020-09-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelvesapp', '0009_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='addedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
