# Generated by Django 3.1 on 2020-10-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelvesapp', '0011_remove_customer_addedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='addedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
